common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: develop
  password: developR1


development:
  <<: *common
  database: dwz_development
test:
  <<: *common
  database: dwz_test
production:
  <<: *common
  database: dwz_production
