common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: develop
  password: developR1


development:
  <<: *common
  database: learn30_development
test:
  <<: *common
  database: learn30_test
production:
  <<: *common
  database: learn30_production
